title:              __aeryz__
email:              abdullaheryz@protonmail.com
description:        Bilgisayar mevzularÄ±
author:             Aeryz
url:                "https://aeryz.github.io"

# Social Profiles
twitter_username:   aeryz2
github_username:    aeryz
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

highlighter: rouge